version: "3.9"

services:
  print-api:
    build: ./print_app         # путь к твоему Dockerfile
    container_name: print-api
    ports:
      - "8000:8000"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    restart: unless-stopped