




version: "3.9"

services:
  cups-server:
    build: ./cups
    container_name: cups-server
    ports:
      - "631:631"
    volumes:
      - cups-data:/var/spool/cups
      - cups-logs:/var/log/cups

  print-api:
    build: ./print_api
    container_name: print-api
    ports:
      - "8000:8000"
    depends_on:
      - cups-server
    environment:
      - CUPS_SERVER=cups-server
      - CUPS_PORT=631

volumes:
  cups-data:
  cups-logs:

